#! /usr/bin/python3
import os

fileLocation = os.path.join(os.getenv("HOME"), ".config/project_list")
projectListFile = open(fileLocation, "r")

projectList = []

valueNames = ["NAME", "PATH", "TYPE", "FILE"]

for v in projectListFile.readlines():
    projectList.append(v.strip("\n").split())
projectListFile.close()


def getObjString(obj):
    objString = f"{obj[0]} {obj[1]} {obj[2]}"
    if len(obj) == 4:
        objString = f"{objString} {obj[3]}"
    return objString


def change_value(name, value):
    value_name = value
    return input(f"Type new project {name} or leave blank to keep it as \"{value_name}\":\n-- ") or value_name


def create_value(name):
    while True:
        if name == "FILE":
            value = input(f"Type a project {name} or press enter to leave it blank:\n-- ")
        elif name == "PATH":
            cur_path = os.getenv("PWD")
            value = input(f"Type a project {name} or press enter to set {name} as {cur_path}:\n--") or cur_path
        else:
            value = input(f"Type a project {name}:\n-- ")
        if not value and name != "FILE":
            print(f"You did not enter a {name}!")
            continue
        else:
            return value


def add_project():
    project = []
    for i in valueNames:
        value = create_value(i)
        if value:
            project.append(value)
    return project


def list_projects():
    for order, obj in enumerate(projectList):
        print(str(f"{order}\t{getObjString(obj)}"))


def printcl(string):
    os.system("clear")
    print(string)


list_projects()

while True:
    try:
        cmd = input("Choose a project from list or run a command (type 'h' for help or 'q' to quit): ")
        
        if cmd == "q":
            printcl("Thank you.")
            break
        elif cmd == "l":
            printcl("")
            list_projects()
        elif cmd == "a":
            project = add_project()
            projectList.append(project)
            printcl(f"{project[0]} added to your project list. Please dont forget to write your changes.")
        elif cmd == "w":
            newProjectListFile = open(fileLocation, "w")
            for i in projectList:
                newProjectListFile.write(f"{getObjString(i)}\n")
            newProjectListFile.close()
            printcl("Your changes has been saved.")
        elif cmd == "d":
            while True:
                printcl("")
                choosen = input("Please choose a valid project id to delete: ")
                if choosen == "q":
                    break
                elif choosen.isdigit() and int(choosen) <= len(projectList):
                    del projectList[int(choosen)]
                    break
                else:
                    printcl("Please enter a valid value!")
                    list_projects()
        elif cmd == "h":
            printcl("If you edit your current project just write project id.\n" +
                    "'q': Quits program. \n" +
                    "'l': List projects \n" +
                    "'a': Add new project \n" +
                    "'w': Write changes to project_list file\n" +
                    "'d': Delete a project") 
        elif cmd.isdigit() and int(cmd) <= len(projectList):
            current_project = projectList[int(cmd)]
            for i, v in enumerate(current_project):
                current_project[i] = change_value(valueNames[i], v)
        else:
            printcl("Please enter a valid project number or command.")
        
    except IndexError:
        printcl("There is no Project on id", cmd, ".\nPlease select one that listed above.")
        continue
