#!/bin/sh


cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
curl -s "https://archlinux.org/mirrorlist/?country=AT&country=BA&country=BG&country=CZ&country=DE&country=GR&country=IR&country=KZ&country=LV&country=LT&country=MK&country=PL&country=RO&country=RS&country=SK&country=SI&country=CH&country=TR&country=UA&protocol=https&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - > /etc/pacman.d/mirrorlist
